version: "3"

tasks:
  default:
    cmds:
      - task -l
  init:
    silent: true
    desc: "Run all init tasks"
    cmds:
      - task init-env
      - task init-packages
  init-env:
    silent: true
    desc: "Initialize .env"
    cmds:
      - |
        if [ ! -f .env ]; then
          echo "➜ Client - Copying .env.example to .env"
          cp .env.example .env
        else
          echo "➜ Client - .env already exists. Skipping..."
        fi
  init-packages:
    silent: true
    desc: "Installs packages using bun, ensure bun is installed in your local environment"
    cmds:
      - echo "➜ Client - Installing packages..."
      - |
        if ! [ -x "$(command -v bun)" ]; then
            echo -e "${YELLOW}⚠️ Error: bun is not installed. Please install bun by running 'brew install oven-sh/bun/bun'${NC}" >&2
            exit 1
        fi
      - bun install
  openapi:
    silent: true
    desc: "Generates code from openapi spec"
    cmds:
      - bunx @rtk-query/codegen-openapi ./src/services/api/config.cjs
  run:
    silent: true
    desc: "Start the client"
    cmds:
      - bunx --bun vite
