export enum Currencies {
  USD = "USD",
  EUR = "EUR",
  JPY = "JPY",
  GBP = "GBP",
  AUD = "AUD",
  CAD = "CAD",
  CHF = "CHF",
  CNY = "CNY",
  SEK = "SEK",
  NZD = "NZD",
  NOK = "NOK",
  KRW = "KRW",
  INR = "INR",
  BRL = "BRL",
  RUB = "RUB",
  ZAR = "ZAR",
  TRY = "TRY",
  MXN = "MXN",
  SGD = "SGD",
  HKD = "HKD",
}
