version: "3"

includes:
  client:
    taskfile: ./client/taskfile.yaml
    dir: client
    internal: true
  server:
    taskfile: server/taskfile.yaml
    dir: server
    internal: true

tasks:
  default:
    silent: true
    cmds:
      - task -l
  db:status:
    silent: true
    cmds:
      - bunx supabase status
  db:start:
    silent: true
    cmds:
      - bunx supabase start
  db:stop:
    silent: true
    cmds:
      - bunx supabase stop
  db:seed:
    silent: true
    cmds:
      - task: server:db:seed
  openapi:
    silent: true
    desc: "Creates openapi spec and generate code"
    cmds:
      - task: server:openapi
      - task: client:openapi
  init:
    silent: true
    desc: "Initialize Dimewise Project"
    cmds:
      - echo
      - echo "Starting Dimewise initialization..."
      - task init-hooks
      - echo "➜ Initializing client..."
      - task: client:init
      - echo "➜ Initializing server..."
      - task: server:init
      - echo "➜ Starting Supabase setup..."
      - task init-supabase
      - echo "➜ Running database migrations..."
      - task: server:db:upgrade
      - echo "➜ Generating OpenAPI documentation..."
      - task openapi
      - echo
      - echo "✅ Dimewise project initialization complete!"
      - echo
      - echo "➜ Please run the following tasks in separate terminals:"
      - echo "   1. task run:server"
      - echo "   2. task run:client"
      - echo
      - echo "Tip - You can use GNU Screen to run them in the background)"
      - echo
  init-hooks:
    silent: true
    desc: "Installs git hooks"
    cmds:
      - echo "➜ Installing git hooks..."
      - cp scripts/hooks/pre-commit .git/hooks/pre-commit
      - cp scripts/hooks/pre-push .git/hooks/pre-push
      - chmod +x .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-push
  init-supabase:
    silent: true
    desc: "Installs and starts Supabase"
    cmds:
      - echo "➜ Starting supabase locally..."
      - bunx supabase start > /dev/null 2>&1
      - |
        echo "➜ Extracting Supabase status..."

        supabase_status=$(bunx supabase status) > /dev/null 2>&1
        api_url=$(echo "$supabase_status" | grep "API URL:" | cut -d ':' -f 2- | tr -d '[:space:]')
        anon_key=$(echo "$supabase_status" | grep "anon key:" | cut -d ':' -f 2- | tr -d '[:space:]')
        db_url=$(echo "$supabase_status" | grep "DB URL:" | cut -d ':' -f 2- | tr -d '[:space:]')
        jwt_key=$(echo "$supabase_status" | grep "JWT secret:" | cut -d ':' -f 2- | tr -d '[:space:]')

        echo "➜ Updating client .env file..."
        sed -i.bak "s|PUBLIC_SUPABASE_URL=.*|PUBLIC_SUPABASE_URL=$api_url|" ./client/.env
        sed -i.bak "s|PUBLIC_SUPABASE_ANON_KEY=.*|PUBLIC_SUPABASE_ANON_KEY=$anon_key|" ./client/.env
        rm ./client/.env.bak

        # Add +asyncpg to the DB_URL
        db_url_with_asyncpg=$(echo "$db_url" | sed "s|postgresql://|postgresql+asyncpg://|")

        echo "➜ Updating server .env file..."
        sed -i.bak "s|DB_URL=.*|DB_URL=$db_url_with_asyncpg|" ./server/.env
        sed -i.bak "s|JWT_TOKEN=.*|JWT_TOKEN=$jwt_key|" ./server/.env
        rm ./server/.env.bak
  run:
    desc: "Start the Dimewise Project"
    cmds:
      - task: client:run
      - task: server:run
  run:client:
    desc: "Start the client"
    cmds:
      - task: client:run
  run:server:
    desc: "Start the server"
    cmds:
      - task: server:run
