//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Category struct {
	ID        uuid.UUID `sql:"primary_key"`
	AccountID uuid.UUID
	Name      string
	Budget    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
