version: "3"

tasks:
  default:
    cmds:
      - task -l
  init:
    silent: true
    desc: "Run all init tasks"
    cmds:
      - task init-env
      - task init-venv
      - task openapi
      - task db:upgrade

  init-env:
    silent: true
    desc: "Initialize .env"
    cmds:
      - |
        if [ ! -f .env ]; then 
          echo "➜ Server - Copying .env.example to .env"
          cp .env.example .env
        else 
          echo "➜ Server - .env already exists. Skipping..."
        fi
  init-venv:
    silent: true
    desc: "Initialize or update virtualenv"
    cmds:
      - |
        if [ -d "venv" ]; then 
          echo "➜ Server - Virtual environment already exists, updating..."; 
        else 
          echo "➜ Server - Creating virtualenv..."; 
          echo
          python3 -m venv venv; 
          echo
        fi
      - echo
      - venv/bin/python3 -m pip install --upgrade pip
      - venv/bin/python3 -m pip install -q -r requirements.txt
      - echo
    sources:
      - requirements.txt
  openapi:
    desc: "Generate openapi spec"
    silent: true
    cmds:
      - LITESTAR_APP=src.main:app venv/bin/litestar schema openapi --output ../openapi.yaml
  db:revision:
    desc: "Generate migration revision"
    silent: true
    cmds:
      - venv/bin/alembic revision --autogenerate -m {{.NAME}}
  db:upgrade:
    desc: "Apply unran migrations"
    silent: true
    cmds:
      - venv/bin/alembic upgrade head
  db:seed:
    desc: "Seed database based on user id"
    silent: true
    cmds:
      - venv/bin/python -m src.utils.seeder {{.USER_ID}}
  run:
    desc: "Start the server"
    cmds:
      - venv/bin/python3 -m uvicorn src.main:app --reload
